const awsconfig =  {
  "AWS_REGION": REACT_APP_REGION,
  "S3_KEY": REACT_APP_ACCESS_KEY_ID,
  "S3_SECRET": REACT_APP_SECRET_ACCESS_KEY,
  "S3_BUCKET": REACT_APP_S3_BUCKET,
};

export default awsconfig;